services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mockdb
    ports:
      - "5432:5432"
  flyway:
    image: boxfuse/flyway
    volumes:
      - ./sql:/src/migrations
    depends_on:
      - db
    command: -url=jdbc:mysql://db:5432/mockdb -user=user -password=password migrate
  populator:
    image: node:23-apline3.20
    volumes:
      - ./data:/src
    depends_on:
      - db
      - flyway